# config.py

# 🎯 METAS DE VENTA
META_MAXIMA = 2500000
META_MEDIA  = 1500000
META_BASE   = 800000

# ⏱️ TIEMPO CORTO
MINUTOS_OFERTA = 3

# CONFIGURACIÓN GOOGLE SHEET
SHEET_ID = "2PACX-1vTUG5PPo2kN1HkP2FY1TNAU9-ehvXqcvE_S9VBnrtQIxS9eVNmnh6Uin_rkvnarDQ"
SHEET_URL = f"https://docs.google.com/spreadsheets/d/e/{SHEET_ID}/pub?gid=2029869540&single=true&output=csv"
URL_FORM_GOOGLE = "" 

# COSTOS FIJOS
COSTO_FLETE_USD = 0.85 
CONDICION_PAGO = "Contado/Transferencia"

CIUDADES_GRATIS = [
    "EL TREBOL", "LOS CARDOS", "LAS ROSAS", "SAN GENARO", "CENTENO", "CASAS", 
    "CAÑADA ROSQUIN", "SAN VICENTE", "SAN MARTIN DE LAS ESCOBAS", "ANGELICA", 
    "SUSANA", "RAFAELA", "SUNCHALES", "PRESIDENTE ROCA", "SA PEREIRA", 
    "CLUCELLAS", "MARIA JUANA", "SASTRE", "SAN JORGE", "LAS PETACAS", 
    "ZENON PEREYRA", "CARLOS PELLEGRINI", "LANDETA", "MARIA SUSANA", 
    "PIAMONTE", "VILA", "SAN FRANCISCO"
]

TOASTS_EXITO = ["🔥 ¡PRECIO CONGELADO!", "💰 ¡AHORRO ACTIVADO!", "📦 ¡STOCK RESERVADO!", "🚀 ¡VAMOS!"]
